version: '3.3'
services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - db_data:/var/lib/postgres/data
    env_file:
      - ./.env

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend

  backend:
    image: ezereul/foodgram:v1.0
    restart: always
    volumes:
      - static_value:/app/backend-static/
      - media_value:/app/backend-media/
    env_file:
      - ./.env
    depends_on:
      - db

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - media_value:/var/html/backend-media/
      - static_value:/var/html/backend-static/
    depends_on:
      - frontend

volumes:
  static_value:
  media_value:
  db_data: