version: '3.3'
services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - db_data:/var/lib/postgres/data
    env_file:
      - ./.env
    ports:
      - 5432:5432

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/
  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - C:/Dev/foodgram-project-react/backend/foodgram_api/media:/var/html/media/
      - C:/Dev/foodgram-project-react/backend/foodgram_api/static:/var/html/static/

volumes:
  static_value:
  media_value:
  db_data: